version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: if [ "$CIRCLE_BRANCH" = "master" ] || [ "$CIRCLE_BRANCH" = "beta" ]; then yarn semantic-release; fi
